# Generated by Django 6.0.2 on 2026-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash on Hand')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gcash_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
