# Generated by Django 6.0.2 on 2026-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_method_alter_payment_gcash_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
    ]
