# Generated by Django 6.0.5 on 2026-05-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffattendance_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendance',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='verified_by',
        ),
    ]
