# Generated by Django 6.0.5 on 2026-05-23 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_staffattendance_admin_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffattendance',
            options={'ordering': ['-date', '-check_in']},
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about this attendance', null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day')], default='pending', max_length=10),
        ),
    ]
