# Generated by Django 6.0.5 on 2026-05-23 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staffattendance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffattendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffschedule',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='staffschedule',
            unique_together={('staff', 'date')},
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
    ]
