# Generated by Django 6.0.2 on 2026-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_sliderimage_delete_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🌸', max_length=10),
        ),
    ]
