# Generated by Django 6.0.2 on 2026-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_sliderimage_options_remove_sliderimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5),
        ),
    ]
