# Generated by Django 6.0.2 on 2026-05-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
