# Generated by Django 6.0.2 on 2026-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash')], default='gcash', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verify', 'Verify'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
