# Generated by Django 6.0.2 on 2026-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_method_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verify', 'Verify'), ('complete', 'Complete Session'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
